---
kind: Service
apiVersion: v1
metadata:
  name: php-service
spec:
  type: ClusterIP
  selector:
    app: php-service
  ports:
    - protocol: TCP
      port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: php-frontend
spec:
  type: NodePort
  selector:
    app: php-frontend
  ports:
    - protocol: TCP
      port: 80
